version: '3.3'

services:
  database:
    image: 'postgres:14.1-alpine'
    environment:
      - POSTGRES_DB=my_task_db
      - POSTGRES_USER=developer
      - POSTGRES_PASSWORD=developer
    ports:
      - '5432:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql